name: Deploy to Remote (Self-Hosted)

on:
  push:
    branches:
      - main

  workflow_dispatch:  

jobs:
  deploy:
    name: Docker Compose Up
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate .env from template
        env:
          ENV_URL: ${{ secrets.ENV_URL }}
          ENV_PROXY_USER: ${{ secrets.ENV_PROXY_USER }}
          ENV_ORGANISATION: ${{ secrets.ENV_ORGANISATION }}
          ENV_TITLE: ${{ secrets.ENV_TITLE }}
        run: |
          envsubst < env.template > .env

      - name: Create Key and Cert Files
        run: |
          mkdir -p ${HOME}/.config/certs
          echo "${{ secrets.PRIVATE_KEY }}" > ${HOME}/.config/certs/private_key.pem
          echo "${{ secrets.FULL_CHAIN_CERT }}" > ${HOME}/.config/certs/certificate.pem

      - name: Run generate_passwords
        run: |
          ./generate_passwords.sh

      - name: Clean up Docker compose
        run: |
          docker compose down

      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose up -d
